import './globals.css'

export const metadata = {
  title: 'My Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="bg-slate-900 text-white min-h-screen">
    <body className="flex">
      <main className="max-w-5xl p-4 mx-auto">
        {children}
      </main>
    </body>
  </html>
  )
}
